services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: messaging
      POSTGRES_PASSWORD: messaging
      POSTGRES_DB: messaging
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      APP_CONFIG_PATH: /app/config/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./config:/app/config:ro
  webhook:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8090:8090"
    entrypoint: ["/app/webhook"]
volumes:
  pgdata:
