package api

import (
	"github.com/gorilla/mux"
	_ "github.com/hakan-sariman/insider-assessment/internal/api/swagger" // generated by: swag init -g cmd/api/main.go -o internal/api/swagger
	httpSwagger "github.com/swaggo/http-swagger"
)

func registerSwagger(r *mux.Router) {
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)
}
